<?= $this->doctype() ?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Admin</title>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css">
  <link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"
    />
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.15.2/css/selectize.bootstrap5.min.css" integrity="sha512-Ars0BmSwpsUJnWMw+KoUKGKunT7+T8NGK0ORRKj+HT8naZzLSIQoOSIIM3oyaJljgLxFi0xImI5oZkAWEFARSA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
  <!-- Custom CSS -->
  <style>
    .navbar-brand {
      color: #fff;
    }
    .navbar-nav {
      justify-content: flex-end;
    }
    .navbar-nav .nav-link {
      color: #fff;
    }
    .bg-primary {
      background-color: #007bff!important;
    }
    .text-white {
      color: #fff!important;
    }
    .form-control:focus {
      box-shadow: none;
      border-color: #007bff;
    }
    .table thead th {
      border-top: none;
    }
    .box {
      display: inline-block;
      width: 250px;
      height: 200px;
      border-radius: 10%;
      background-color: #f5f5f5;
      margin: 20px;
      padding: 20px;
      text-align: center;
      line-height: 150px;
      font-size: 50px;
      transition:200ms;
    }
    
    .box:hover{
      box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
    }
  </style>
</head>
<body>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
     
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav"> 
            
          <li class="nav-item">
            <a class="nav-link" style="color:white" href="/admin">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" style="color:white" href="/admin/functions">Functions</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" style="color:white" href="/admin/notifications">Notifications</a>
          </li>
          <li class="nav-item">
            <a class="nav-link"  style="color:white" href="/api">Json</a>
          </li>
          <?if (isset($_COOKIE['login'])) {?>
          <li class="nav-item">
            <a class="nav-link" href="/logout">
                <i style="color:white" class="bi bi-box-arrow-right"></i> 
            </a>
            </li>
          <? } ?>
        </ul>
      </div>
    </div>
  </nav>
  

  <div class="container my-5">

  <?= $this->content ?>



  </div>
  <!-- Bootstrap JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.15.2/js/selectize.min.js" integrity="sha512-IOebNkvA/HZjMM7MxL0NYeLYEalloZ8ckak+NDtOViP7oiYzG5vn6WVXyrJDiJPhl4yRdmNAG49iuLmhkUdVsQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
</body>
</html>
