
<h1 class="pb-2">Create notification</h1>
<form method="POST"  action="/admin/notifications/add">
    <div class="col mb-3" style="background-color:rgba(0,0,0,0.05); padding: 40px; border-radius:20px">
        
        <div class="row">
             <div class="col-6">
            <input type="text" style="width: 80% ; margin-bottom:30px" name="title" class="form-control" placeholder="title" id="title">
            </div >
            <div class="col-6">
                
            
            <select id="type" style="width: 50%;" name="type" placeholder="Type">
                
                <option value="0" selected>Text</option>
                <option value="1">Yes/No question</option>
            </select>
            </div >
        </div>
        <div >
            <input type="text"  name="intro" class="form-control" placeholder="intro" id="intro">
        </div>
       
    </div>
    <div class="container">
    <p>Send to:</p>
        <select id="demo"  name="sendto">
        <option selected value="all">All</option>
        <option value="public">public</option>
        <option value="awreal.sk">awreal.sk</option>
        <option value="LISP">LISP</option>
        <option value="C++">C++</option>
        <option value="jQuery">jQuery</option>
        <option value="Ruby">Ruby</option>
        </select>
    </div>
    
    <div class="container mt-2">
        <p>Content:</p>
        <textarea id="summernote" name="editordata"></textarea>
    </div>
    <div class="container mt-5 ">
        <button type="submit" class="btn btn-primary" style="z-index:2">Send</button>
    </div>
    
</form>
<script>
    $(document).ready(function() {
            $('#summernote').summernote();
           let select =  $('#demo').selectize({
                maxItems: 50
            });
            console.log(select);
            
            $('#type').selectize({
                
            });


    });
    
    
   
    
</script>

